### PR TITLE
linux support/g++

### PR DESCRIPTION
**Pull request by ghost**
There's like 3 spots where I just broke stuff just to make it compile because I don't know cpp and I was getting a headache trying to figure out how to do it properly

### CODE REVIEW

**Comment by ghost** [comment]
Image
this is wrong but g++ refused to compile if I didn't give it another argument, I don't know what was forcing it to have 3 arguments.

**Comment by ghost** [comment]
Image
sync didn't want the same name as Sync so i had to change it

**Comment by ghost** [comment]
image
I had to update the g++ version because it was causing compiler errors since you are using new c++ stuff

**Comment by ghost** [comment]
image
I have no idea how to find out what caused this to happen

**Comment by Blenderiste09** [comment]
Those are not fixes.
+ I and Jake have fixed this in a proper way

**Pull request closed without merging**
